import interLogo from '../assets/bank-inter.webp'
import nubankLogo from '../assets/bank-nubank.webp'

export const API_BASE = 'http://localhost:3000/api'
export const APP_VERSION = 'Wallet Hub v1.1.1'
export const DEV_SIGNATURE = 'Flamma Digital'

export const DASHBOARD_ITEMS = {
  '115ae3ff-be4b-4330-8278-7de1d99e3a7b': 'Inter',
  '481ff23b-9bf0-4618-8c94-f046a27fbbc9': 'Nubank',
}

export const BANK_BRANDING = {
  '115ae3ff-be4b-4330-8278-7de1d99e3a7b': {
    name: 'Inter',
    logo: interLogo,
  },
  '481ff23b-9bf0-4618-8c94-f046a27fbbc9': {
    name: 'Nubank',
    logo: nubankLogo,
  },
}

export const COPY = {
  en: {
    homeBadge: 'Data Wallet for Open Finance',
    homeTitle: 'All your accounts in one place',
    homeSubtitle: 'Connect your bank accounts and view your financial life in one simple dashboard.',
    homePrimaryCta: 'Start now',
    homeSecondaryCta: 'Explore project',
    homePreviewTitle: 'Connected Accounts',
    homePreviewTotalLabel: 'Total Wealth',
    overview: 'Overview',
    subtitle: 'General view of your financial data.',
    bankAccounts: 'Bank Accounts',
    creditCards: 'Credit Cards',
    investments: 'Investments',
    cards: 'cards',
    accounts: 'accounts',
    positions: 'positions',
    usedOf: 'Used of',
    limitUsage: 'limit usage',
    classesAndAssets: '1 class - 1 asset',
    fixedIncome: 'Fixed Income',
    balanceEvolution: 'Balance Evolution',
    monthlyView: 'Monthly view',
    refresh: 'Refresh',
    connections: 'All connections',
    navOverview: 'Overview',
    navFlow: 'Flow',
    navAssets: 'Assets',
    navConnections: 'Connections',
    flowTitle: 'Cash Flow',
    flowSubtitle: 'Expenses, income and account transactions.',
    assetsTitle: 'Assets',
    assetsSubtitle: 'Your investments and movements.',
    connectionsTitle: 'Data Passport',
    connectionsSubtitle: 'Connect, view, and manage your financial connections.',
    connectionsDataPassportTitle: 'Data Passport',
    connectionsDataPassportSubtitle: 'Connect, view, and manage your financial connections.',
    connectionsNewConnection: 'New connection',
    connectionsExportBackup: 'Export',
    connectionsImportBackup: 'Import',
    connectionsActiveLabel: 'active',
    connectionsSyncedToday: 'Today',
    connectionsSyncedYesterday: '1 day ago',
    connectionsSyncedDaysAgo: '{days} days ago',
    connectionsSeeDetails: 'See details',
    connectionsPartnerApps: 'Partner Apps',
    connectionsNoPartnerApps: 'No partner app is accessing your data.',
    connectionsNoConnections: 'No active connections found.',
    connectionsBankLabel: 'Bank',
    connectionsBack: 'Connections',
    connectionsUpdate: 'Update',
    connectionsDelete: 'Remove',
    connectionsItemIdLabel: 'Item ID',
    connectionsMovements: 'movements',
    connectionsSyncLabel: 'Synchronized',
    connectionsAutoUpdateLabel: 'Auto-updates automatically',
    connectionsManualLabel: 'Manual',
    connectionsCredentialsTitle: 'New Pluggy connection',
    connectionsClientIdLabel: 'Pluggy Client ID',
    connectionsClientSecretLabel: 'Pluggy Client Secret',
    connectionsItemIdsLabel: 'Item IDs (comma or line separated)',
    connectionsClientIdPlaceholder: 'Paste your Client ID',
    connectionsClientSecretPlaceholder: 'Paste your Client Secret',
    connectionsItemIdsPlaceholder: 'item_id_1, item_id_2',
    connectionsCancelLabel: 'Cancel',
    connectionsSaveCredentialsLabel: 'Save and connect',
    connectionsCredentialsError: 'Fill Client ID, Client Secret, and at least one Item ID.',
    connectionsDeleteConfirm: 'Do you want to remove this connection from your item IDs?',
    connectionsModalTitle: 'New connection',
    connectionsAddConnectionType: 'How do you want to add your data?',
    connectionsAutomatedTitle: 'Automated Connection (Pluggy)',
    connectionsAutomatedSubtitle: 'Sync automatically using your API keys.',
    connectionsManualTitle: 'Manual Import (CSV)',
    connectionsManualSubtitle: 'Upload your exported statements.',
    connectionsManualImportTitle: 'Manual Import',
    connectionsBackLabel: 'Back',
    connectionsManualDragDrop: 'Drag and drop your CSV file here',
    connectionsManualOrUpload: 'or',
    connectionsManualBrowseFiles: 'Browse files',
    connectionsCsvInstitutionLabel: 'Institution Name',
    connectionsCsvInstitutionPlaceholder: 'e.g. Inter, Nubank',
    connectionsCsvAccountLabel: 'Account Name',
    connectionsCsvAccountPlaceholder: 'e.g. Main Checking',
    connectionsPhysicalTitle: 'Physical Wallet (Cash)',
    connectionsPhysicalConnectionLabel: 'Physical Wallet',
    connectionsPhysicalWalletsLabel: 'Physical Wallets',
    connectionsPhysicalSubtitle: 'Track physical cash or manual balances.',
    connectionsPhysicalWalletNameLabel: 'Wallet Name',
    connectionsPhysicalWalletNamePlaceholder: 'Pocket Money',
    connectionsPhysicalBalanceLabel: 'Current Balance',
    connectionsPhysicalAddedTransaction: 'Physical money added',
    connectionsPhysicalCategory: 'Physical wallet',
    connectionsPhysicalValidationError: 'Fill Wallet Name and Current Balance.',
    connectionsAddTransaction: 'Add transaction',
    connectionsTransactionsLabel: 'Transactions',
    connectionsTransactionDescriptionLabel: 'Description',
    connectionsTransactionDescriptionPlaceholder: 'Groceries, ATM Withdrawal...',
    connectionsTransactionAmountLabel: 'Amount',
    connectionsTransactionTypeLabel: 'Type',
    connectionsTransactionDateLabel: 'Date',
    connectionsSaveTransactionLabel: 'Save transaction',
    connectionsManualTransactionValidation: 'Fill description and a valid amount.',
    connectionsManualTransactionSaveError: 'Could not save this transaction.',
    connectionsDisconnectLabel: 'Disconnect Pluggy',
    connectionsDisconnectConfirm: 'Do you want to completely disconnect Pluggy and clear all saved credentials?',
    copyFieldLabel: 'Copy',
    copiedFieldLabel: 'Copied',
    showSecretLabel: 'Show',
    hideSecretLabel: 'Hide',
    lightMode: 'Light',
    darkMode: 'Dark',
    classes: 'Classes',
    institutions: 'Institutions',
    loadingDashboard: 'Loading dashboard...',
    dashboardUnavailable: 'Dashboard unavailable',
    dashboardUnavailableInstruction: 'You need to add a new connection.',
    dashboardLoginLinkLabel: 'Go to login',
    fallbackLoadError: 'Unexpected error while loading dashboard data.',
    loadDashboardError: 'Failed to load dashboard data.',
    unknownItem: 'an item',
    partialRefreshPrefix: 'Some connections failed to refresh',
    partialRefreshSuffix: 'Showing partial data.',
    accountUnit: '1 account',
    limitLabel: 'Limit:',
    mastercardGold: 'Mastercard Gold',
    assetsLabel: 'assets',
    collapse: 'Collapse',
    expand: 'Expand',
    monthlyCashFlow: 'Monthly Cash Flow',
    recentTransactions: 'Recent Transactions',
    spendingByCategory: 'Spending by Category',
    upcomingBills: 'Upcoming Bills',
    incomeLabel: 'Income',
    expensesLabel: 'Expenses',
    noTransactions: 'No transactions available.',
    noCategoryData: 'No category data for this month.',
    noUpcomingBills: 'No credit card bills available.',
    uncategorized: 'Uncategorized',
    othersCategory: 'Others',
    flowExpensesTitle: 'Expenses',
    flowExpensesSubtitle: 'Categorized transactions',
    flowIncomeTitle: 'Income',
    flowIncomeSubtitle: 'Categorized income',
    flowNoIncome: 'No income this month.',
    flowPendingTitle: 'Future Expenses',
    flowPendingSubtitle: 'Pending transactions',
    flowSoonTitle: 'Coming Soon',
    flowSoonSubtitle: 'New flow card',
    flowAnalysisSoonTitle: 'Coming Soon',
    flowAnalysisSoonSubtitle: 'New analysis module under construction.',
    flowProjectedBalanceTitle: 'Projected Balance',
    flowProjectedBalanceSubtitle: 'Bank accounts - Credit card bills',
    flowProjectedBalanceInBankLabel: 'In account',
    flowProjectedBalanceBillsLabel: 'Bills',
    flowFinancialHealthTitle: 'Financial Health',
    flowFinancialHealthSubtitle: 'Track your progress with simple metrics.',
    flowFinancialHealthSavings: 'Savings',
    flowFinancialHealthDebt: 'Debt',
    flowFinancialHealthSpending: 'Spending',
    flowNoExpenses: 'No expenses this month.',
    flowNoPending: 'No pending this month.',
    usedLabel: 'Used',
    ofIncomeSpent: 'of income spent',
    dueInLabel: 'Due on',
    dayLabel: 'day',
    showAll: 'Show all',
    assetsPortfolioLabel: 'Portfolio',
    assetsValueLabel: 'Current value',
    assetsFixedIncomeLabel: 'FIXED INCOME',
    assetsUnknownType: 'Unknown type',
    assetsMovementsLabel: 'Movements',
    assetsBuyLabel: 'BUY',
    assetsBalanceLabel: 'Balance',
    assetsProfitabilityLabel: 'Profitability',
    assetsInvestedValueLabel: 'Invested value',
    assetsNotAvailable: 'N/A',
    noAssetsData: 'No investment assets available.',
    allAccounts: 'All accounts',
    searchTransactionPlaceholder: 'Search transaction...',
    allFilter: 'All',
    incomesFilter: 'Income',
    expensesFilter: 'Expenses',
    transactionCount: 'transactions',
    balanceLabel: 'Balance',
    balanceDifferenceLabel: 'Difference Balance',
    balanceIncomeLabel: 'Income Balance',
    balanceExpenseLabel: 'Expense Balance',
    openingBalanceLabel: 'Opening Balance',
    appVersion: APP_VERSION,
    developedByLabel: 'developed by',
    developerSignature: DEV_SIGNATURE,
    apiOperationalStatus: 'API operational',
    lastSyncedLabel: 'Last synced',
    notSyncedYet: 'just now',
    fhStatusGood: 'Good',
    fhStatusFair: 'Fair',
    fhStatusPoor: 'Poor',
    fhStatusLow: 'Low',
    fhStatusMedium: 'Medium',
    fhStatusHigh: 'High',
    fhStatusWatch: 'Watch',
    fhStatusDanger: 'Danger',
  },
  pt: {
    homeBadge: 'Data Wallet para Open Finance',
    homeTitle: 'Todas as suas contas em um só lugar',
    homeSubtitle: 'Conecte suas contas bancárias e visualize sua vida financeira em um dashboard simples.',
    homePrimaryCta: 'Começar agora',
    homeSecondaryCta: 'Explorar projeto',
    homePreviewTitle: 'Contas Conectadas',
    homePreviewTotalLabel: 'Patrimônio Total',
    overview: 'Visão geral',
    subtitle: 'Visão geral dos seus dados financeiros.',
    bankAccounts: 'Contas bancárias',
    creditCards: 'Cartões de crédito',
    investments: 'Investimentos',
    cards: 'cartões',
    accounts: 'contas',
    positions: 'posições',
    usedOf: 'Utilizado de',
    limitUsage: 'limite usado',
    classesAndAssets: '1 classe - 1 ativo',
    fixedIncome: 'Renda Fixa',
    balanceEvolution: 'Evolução do saldo',
    monthlyView: 'Visão mensal',
    refresh: 'Atualizar',
    connections: 'Todas conexões',
    navOverview: 'Visão geral',
    navFlow: 'Fluxo',
    navAssets: 'Ativos',
    navConnections: 'Conexões',
    flowTitle: 'Fluxo de Caixa',
    flowSubtitle: 'Despesas, receitas e movimentações das suas contas.',
    assetsTitle: 'Ativos de Investimento',
    assetsSubtitle: 'Seus investimentos e movimentações.',
    connectionsTitle: 'Passaporte de Dados',
    connectionsSubtitle: 'Conecte, visualize e gerencie suas conexões financeiras.',
    connectionsDataPassportTitle: 'Passaporte de Dados',
    connectionsDataPassportSubtitle: 'Conecte, visualize e gerencie suas conexões financeiras.',
    connectionsNewConnection: 'Nova conexão',
    connectionsExportBackup: 'Exportar',
    connectionsImportBackup: 'Importar',
    connectionsActiveLabel: 'ativas',
    connectionsSyncedToday: 'Hoje',
    connectionsSyncedYesterday: '1 dia atrás',
    connectionsSyncedDaysAgo: '{days} dias atrás',
    connectionsSeeDetails: 'Ver detalhes',
    connectionsPartnerApps: 'Apps parceiros',
    connectionsNoPartnerApps: 'Nenhum app parceiro está acessando seus dados.',
    connectionsNoConnections: 'Nenhuma conexão ativa encontrada.',
    connectionsBankLabel: 'Banco',
    connectionsBack: 'Conexões',
    connectionsUpdate: 'Atualizar',
    connectionsDelete: 'Remover',
    connectionsItemIdLabel: 'Item ID',
    connectionsMovements: 'movimentações',
    connectionsSyncLabel: 'Sincronizado',
    connectionsAutoUpdateLabel: 'Atualiza automaticamente',
    connectionsManualLabel: 'Manual',
    connectionsCredentialsTitle: 'Nova conexão Pluggy',
    connectionsClientIdLabel: 'Pluggy Client ID',
    connectionsClientSecretLabel: 'Pluggy Client Secret',
    connectionsItemIdsLabel: 'Item IDs (separados por vírgula ou linha)',
    connectionsClientIdPlaceholder: 'Cole seu Client ID',
    connectionsClientSecretPlaceholder: 'Cole seu Client Secret',
    connectionsItemIdsPlaceholder: 'item_id_1, item_id_2',
    connectionsCancelLabel: 'Cancelar',
    connectionsSaveCredentialsLabel: 'Salvar e conectar',
    connectionsCredentialsError: 'Preencha Client ID, Client Secret e pelo menos um Item ID.',
    connectionsDeleteConfirm: 'Deseja remover esta conexão dos seus item IDs?',
    connectionsModalTitle: 'Nova conexão',
    connectionsAddConnectionType: 'Como deseja adicionar seus dados?',
    connectionsAutomatedTitle: 'Conexão Automatizada (Pluggy)',
    connectionsAutomatedSubtitle: 'Sincronize automaticamente usando suas chaves de API.',
    connectionsManualTitle: 'Importação Manual (CSV)',
    connectionsManualSubtitle: 'Faça upload dos seus extratos exportados.',
    connectionsManualImportTitle: 'Importação Manual',
    connectionsBackLabel: 'Voltar',
    connectionsManualDragDrop: 'Arraste e solte seu arquivo CSV aqui',
    connectionsManualOrUpload: 'ou',
    connectionsManualBrowseFiles: 'Procurar arquivos',
    connectionsCsvInstitutionLabel: 'Nome da instituição',
    connectionsCsvInstitutionPlaceholder: 'ex.: Inter, Nubank',
    connectionsCsvAccountLabel: 'Nome da conta',
    connectionsCsvAccountPlaceholder: 'ex.: Conta Principal',
    connectionsPhysicalTitle: 'Carteira Física (Dinheiro)',
    connectionsPhysicalConnectionLabel: 'Carteira Física',
    connectionsPhysicalWalletsLabel: 'Carteiras físicas',
    connectionsPhysicalSubtitle: 'Acompanhe dinheiro físico ou saldos manuais.',
    connectionsPhysicalWalletNameLabel: 'Nome da carteira',
    connectionsPhysicalWalletNamePlaceholder: 'Dinheiro da carteira',
    connectionsPhysicalBalanceLabel: 'Saldo atual',
    connectionsPhysicalAddedTransaction: 'Dinheiro físico adicionado',
    connectionsPhysicalCategory: 'Carteira física',
    connectionsPhysicalValidationError: 'Preencha Nome da carteira e Saldo atual.',
    connectionsAddTransaction: 'Adicionar transação',
    connectionsTransactionsLabel: 'Transações',
    connectionsTransactionDescriptionLabel: 'Descrição',
    connectionsTransactionDescriptionPlaceholder: 'Mercado, Saque no caixa...',
    connectionsTransactionAmountLabel: 'Valor',
    connectionsTransactionTypeLabel: 'Tipo',
    connectionsTransactionDateLabel: 'Data',
    connectionsSaveTransactionLabel: 'Salvar transação',
    connectionsManualTransactionValidation: 'Preencha descrição e um valor válido.',
    connectionsManualTransactionSaveError: 'Não foi possível salvar esta transação.',
    connectionsDisconnectLabel: 'Desconectar Pluggy',
    connectionsDisconnectConfirm: 'Deseja desconectar completamente a Pluggy e limpar todas as credenciais salvas?',
    copyFieldLabel: 'Copiar',
    copiedFieldLabel: 'Copiado',
    showSecretLabel: 'Mostrar',
    hideSecretLabel: 'Ocultar',
    lightMode: 'Claro',
    darkMode: 'Escuro',
    classes: 'Classes',
    institutions: 'Instituições',
    loadingDashboard: 'Carregando dashboard...',
    dashboardUnavailable: 'Dashboard indisponível',
    dashboardUnavailableInstruction: 'Você precisa adicionar uma nova conexão.',
    dashboardLoginLinkLabel: 'Ir para o login',
    fallbackLoadError: 'Erro inesperado ao carregar o dashboard.',
    loadDashboardError: 'Falha ao carregar os dados do dashboard.',
    unknownItem: 'um item',
    partialRefreshPrefix: 'Algumas conexões falharam ao atualizar',
    partialRefreshSuffix: 'Exibindo dados parciais.',
    accountUnit: '1 conta',
    limitLabel: 'Limite:',
    mastercardGold: 'Mastercard Gold',
    assetsLabel: 'ativos',
    collapse: 'Recolher',
    expand: 'Expandir',
    monthlyCashFlow: 'Fluxo mensal',
    recentTransactions: 'Últimas transações',
    spendingByCategory: 'Gastos por categoria',
    upcomingBills: 'Próximos vencimentos',
    incomeLabel: 'Entradas',
    expensesLabel: 'Saídas',
    noTransactions: 'Sem transações disponíveis.',
    noCategoryData: 'Sem dados de categoria neste mês.',
    noUpcomingBills: 'Sem faturas de cartão disponíveis.',
    uncategorized: 'Sem categoria',
    othersCategory: 'Outros',
    flowExpensesTitle: 'Despesas',
    flowExpensesSubtitle: 'Transações categorizadas',
    flowIncomeTitle: 'Receitas',
    flowIncomeSubtitle: 'Receitas categorizadas',
    flowNoIncome: 'Sem receitas no mês.',
    flowPendingTitle: 'Despesas futuras',
    flowPendingSubtitle: 'Transações pendentes',
    flowSoonTitle: 'Em breve',
    flowSoonSubtitle: 'Novo card de fluxo',
    flowAnalysisSoonTitle: 'Em breve',
    flowAnalysisSoonSubtitle: 'Novo módulo de análise em construção.',
    flowProjectedBalanceTitle: 'Saldo projetado',
    flowProjectedBalanceSubtitle: 'Contas bancárias - Faturas de cartão',
    flowProjectedBalanceInBankLabel: 'Em conta',
    flowProjectedBalanceBillsLabel: 'Faturas',
    flowFinancialHealthTitle: 'Saúde financeira',
    flowFinancialHealthSubtitle: 'Acompanhe seu progresso com métricas simples.',
    flowFinancialHealthSavings: 'Poupança',
    flowFinancialHealthDebt: 'Dívidas',
    flowFinancialHealthSpending: 'Gastos',
    flowNoExpenses: 'Sem despesas no mês.',
    flowNoPending: 'Sem pendências no mês.',
    usedLabel: 'Utilizado',
    ofIncomeSpent: 'da renda gasta',
    dueInLabel: 'Vence em',
    dayLabel: 'dia',
    showAll: 'Ver tudo',
    assetsPortfolioLabel: 'Carteira',
    assetsValueLabel: 'Valor atual',
    assetsFixedIncomeLabel: 'RENDA FIXA',
    assetsUnknownType: 'Tipo desconhecido',
    assetsMovementsLabel: 'Movimentações',
    assetsBuyLabel: 'COMPRA',
    assetsBalanceLabel: 'Saldo',
    assetsProfitabilityLabel: 'Rentabilidade',
    assetsInvestedValueLabel: 'Valor investido',
    assetsNotAvailable: 'N/D',
    noAssetsData: 'Sem ativos de investimentos disponíveis.',
    allAccounts: 'Todas contas',
    searchTransactionPlaceholder: 'Buscar transação...',
    allFilter: 'Todos',
    incomesFilter: 'Entradas',
    expensesFilter: 'Saídas',
    transactionCount: 'transações',
    balanceLabel: 'Saldo',
    balanceDifferenceLabel: 'Saldo de diferença',
    balanceIncomeLabel: 'Saldo de entradas',
    balanceExpenseLabel: 'Saldo de saídas',
    openingBalanceLabel: 'Saldo de Abertura',
    appVersion: APP_VERSION,
    developedByLabel: 'desenvolvido por',
    developerSignature: DEV_SIGNATURE,
    apiOperationalStatus: 'API operacional',
    lastSyncedLabel: 'Última sincronização',
    notSyncedYet: 'agora mesmo',
    fhStatusGood: 'Bom',
    fhStatusFair: 'Razoável',
    fhStatusPoor: 'Ruim',
    fhStatusLow: 'Baixa',
    fhStatusMedium: 'Média',
    fhStatusHigh: 'Alta',
    fhStatusWatch: 'Atenção',
    fhStatusDanger: 'Perigo',
  },
}

export const getArrayResults = (payload) => {
  if (Array.isArray(payload)) return payload
  if (Array.isArray(payload?.results)) return payload.results
  return []
}

export const getCreditLimit = (account) =>
  account?.creditData?.creditLimit ??
  account?.creditData?.limit ??
  account?.creditLimit ??
  account?.credit?.limit ??
  0

export const getInvestmentValue = (investment) =>
  Number(investment?.balance) || Number(investment?.amount) || Number(investment?.value) || 0

export const getInstitutionName = (entry) => {
  if (entry?.itemId && BANK_BRANDING[entry.itemId]?.name) {
    return BANK_BRANDING[entry.itemId].name
  }

  const marketingName =
    entry?.marketingName ||
    entry?.item?.connector?.marketingName ||
    entry?.connector?.marketingName ||
    null

  if (marketingName) return marketingName

  const name = entry?.name || entry?.item?.connector?.name || entry?.connector?.name || null
  if (name) return name

  return DASHBOARD_ITEMS[entry?.itemId] || 'Unknown Institution'
}

export const getBankLogo = (entry) => entry?.logo || BANK_BRANDING[entry?.itemId]?.logo || null

export const getFriendlyAccountLabel = (account, language = 'pt', fallbackLabel = 'Unknown account') => {
  if (!account) return fallbackLabel

  const institutionName = getInstitutionName(account)
  const accountType = String(account?.type || account?.accountType || 'BANK').toUpperCase()
  const isManualWallet = String(account?.connectionType || '').toUpperCase() === 'MANUAL_WALLET' || String(account?.connectionType || '').toUpperCase() === 'PHYSICAL_WALLET'
  const isCreditAccount = accountType === 'CREDIT'

  const typeLabel = isManualWallet
    ? (language === 'pt' ? 'Carteira Física' : 'Physical Wallet')
    : language === 'pt'
      ? (isCreditAccount ? 'Cartão de Crédito' : 'Conta Corrente')
      : (isCreditAccount ? 'Credit Card' : 'Checking Account')

  return `${institutionName} (${typeLabel})`
}
